version: '3.6'

services:
  db:
    image: mariadb:${MARIADB_VERSION:-latest}
    container_name: ${COMPOSE_PROJECT_NAME}_mysql
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD:-password}
      - MYSQL_USER=${DATABASE_USER:-root}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD:-password}
      - MYSQL_DATABASE=${COMPOSE_PROJECT_NAME:-wordpress}

  wordpress:
    depends_on:
      - db
    image: wordpress:${WORDPRESS_VERSION:-latest}
    container_name: ${COMPOSE_PROJECT_NAME:-wordpress}
    ports:
      - "8089:80"
    restart: always
    environment:
      - WORDPRESS_DB_NAME=${COMPOSE_PROJECT_NAME:-wordpress}
      - WORDPRESS_TABLE_PREFIX=${WORDPRESS_TABLE_PREFIX:-wp_}
      - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST:-db}
      - WORDPRESS_DB_USER=${DATABASE_USER:-root}
      - WORDPRESS_DB_PASSWORD=${DATABASE_PASSWORD:-password}
    working_dir: /var/www/html
    volumes:
      - ${WORDPRESS_DATA_DIR}/core:/var/www/html
      - ${WORDPRESS_WP_CONTENT_DATA_DIR}/wp-content:/var/www/html/wp-content
      - ${WORDPRESS_WP_CONTENT_DATA_DIR:-./uploads.ini}:/usr/local/etc/php/conf.d/uploads.ini

  phpmyadmin:
      depends_on:
        - db
      image: phpmyadmin/phpmyadmin:${PHPMYADMIN_VERSION:-latest}
      container_name: ${COMPOSE_PROJECT_NAME}_phpmyadmin
      restart: always
      ports:
        - ${PHPMYADMIN_PORT}:80
      environment:
        PMA_HOST: db
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-password}
volumes:
  db_data: